import type { Song, MoveEvent } from "@/app/types/song";

/**
 * Builds a complete HamBuild DTA file from song data
 * Converts Boomy's JSON timeline format to HamBuild's Lisp-like DTA format
 */
export class HamBuildDtaBuilder {
  private song: Song;
  private audioPath: string | null;
  private coverImagePath: string | null;

  constructor(song: Song, audioPath?: string | null, coverImagePath?: string | null) {
    this.song = song;
    this.audioPath = audioPath || null;
    this.coverImagePath = coverImagePath || null;
  }

  /**
   * Generate the complete DTA content
   */
  generateDta(): string {
    const lines: string[] = [];

    // Header comment
    lines.push("; Auto-generated by Boomy Editor");
    lines.push("; Song: " + this.escapeDtaString(this.song.name || "Unknown"));
    lines.push("");

    // Add metadata fields if available
    lines.push(...this.buildMetadataFields());
    lines.push("");

    // Add audio file reference
    if (this.audioPath) {
      const audioFileName = this.audioPath.split("/").pop();
      lines.push(`(audio "${audioFileName}")`);
    }

    // Add cover art if available
    if (this.coverImagePath) {
      const coverFileName = this.coverImagePath.split("/").pop();
      lines.push(`(album_art "${coverFileName}")`);
    }

    // Add tempo map if there are tempo changes
    if (this.song.tempoChanges && this.song.tempoChanges.length > 0) {
      lines.push(...this.buildTempoMap());
    }

    // Add party jumps if available
    if (this.song.partyJumps && this.song.partyJumps.length > 0) {
      lines.push(...this.buildPartyJumps());
    }

    // Add battle section if available
    if (this.song.battleSteps && this.song.battleSteps.length > 0) {
      lines.push(...this.buildBattle());
    }

    // Add events section if there are any song events
    if (this.song.events && this.song.events.length > 0) {
      lines.push(...this.buildEventsSection());
    }

    lines.push("");

    // Build each routine
    lines.push(...this.buildRoutine("expert", this.song.timeline.expert.moves));

    // Add expert camera events if available
    if (this.song.timeline.expert.cameras && this.song.timeline.expert.cameras.length > 0) {
      lines.push("");
      lines.push(...this.buildCameraEvents("expert", this.song.timeline.expert.cameras));
    }

    if (this.song.timeline.medium && this.song.timeline.medium.moves.length > 0) {
      lines.push("");
      lines.push(...this.buildRoutine("medium", this.song.timeline.medium.moves));

      // Add medium camera events if available
      if (this.song.timeline.medium.cameras && this.song.timeline.medium.cameras.length > 0) {
        lines.push("");
        lines.push(...this.buildCameraEvents("medium", this.song.timeline.medium.cameras));
      }
    }

    if (this.song.timeline.easy && this.song.timeline.easy.moves.length > 0) {
      lines.push("");
      lines.push(...this.buildRoutine("easy", this.song.timeline.easy.moves));

      // Add easy camera events if available
      if (this.song.timeline.easy.cameras && this.song.timeline.easy.cameras.length > 0) {
        lines.push("");
        lines.push(...this.buildCameraEvents("easy", this.song.timeline.easy.cameras));
      }
    }

    // Beginner is optional - only add if supereasy has moves
    if (this.song.supereasy && this.song.supereasy.length > 0) {
      lines.push("");
      lines.push(...this.buildRoutine("beginner", this.song.supereasy));
    }

    return lines.join("\n");
  }

  /**
   * Build metadata fields for HamBuild DTA format
   */
  private buildMetadataFields(): string[] {
    const lines: string[] = [];
    const meta = this.song.meta;

    if (!meta) {
      return lines;
    }

    // Song name/title
    if (meta.name) {
      lines.push(`(name "${this.escapeDtaString(meta.name)}")`);
    }

    // Artist
    if (meta.artist) {
      lines.push(`(artist "${this.escapeDtaString(meta.artist)}")`);
    }

    // Album name
    if (meta.album_name) {
      lines.push(`(album_name "${this.escapeDtaString(meta.album_name)}")`);
    }

    // BPM
    if (meta.bpm) {
      lines.push(`(bpm ${meta.bpm})`);
    }

    // Song ID
    if (meta.songid) {
      lines.push(`(songid ${meta.songid})`);
    }

    // Rank/difficulty rating
    if (meta.rank !== undefined && meta.rank !== null) {
      lines.push(`(rank ${meta.rank})`);
    }

    // DJ Intensity Rank
    if (meta.dj_intensity_rank !== undefined && meta.dj_intensity_rank !== null) {
      lines.push(`(dj_intensity_rank ${meta.dj_intensity_rank})`);
    }

    // Year Released
    if (meta.year_released) {
      lines.push(`(year_released ${meta.year_released})`);
    }

    // Preview start/end
    if (meta.preview) {
      if (meta.preview.start !== undefined) {
        lines.push(`(preview_start_time ${meta.preview.start})`);
      }
      if (meta.preview.end !== undefined) {
        lines.push(`(preview_end_time ${meta.preview.end})`);
      }
    }

    // Default character
    if (meta.default_character) {
      lines.push(`(default_character ${meta.default_character})`);
    }

    // Backup character
    if (meta.backup_character) {
      lines.push(`(backup_character ${meta.backup_character})`);
    }

    // Default character alternative outfit
    if (meta.default_character_alt) {
      lines.push(`(default_character_alt ${meta.default_character_alt})`);
    }

    // Backup character alternative outfit
    if (meta.backup_character_alt) {
      lines.push(`(backup_character_alt ${meta.backup_character_alt})`);
    }

    // Default venue
    if (meta.default_venue) {
      lines.push(`(default_venue ${meta.default_venue})`);
    }

    // Backup venue
    if (meta.backup_venue) {
      lines.push(`(backup_venue ${meta.backup_venue})`);
    }

    // Gender
    if (meta.gender) {
      lines.push(`(gender ${meta.gender})`);
    }

    // Game origin
    if (meta.game_origin) {
      lines.push(`(game_origin ${meta.game_origin})`);
    }

    return lines;
  }

  /**
   * Build tempo map from tempo changes
   */
  private buildTempoMap(): string[] {
    const lines: string[] = [];

    if (!this.song.tempoChanges || this.song.tempoChanges.length === 0) {
      return lines;
    }

    lines.push("(tempomap");
    
    // Sort by measure to ensure chronological order
    const sortedTempos = [...this.song.tempoChanges].sort((a, b) => a.measure - b.measure);
    
    for (const tempo of sortedTempos) {
      // Shift measure 0 to 1 (HamBuild uses 1-based indexing)
      const hamBuildMeasure = Math.max(1, tempo.measure);
      lines.push(`  (${hamBuildMeasure} ${tempo.bpm})`);
    }
    
    lines.push(")");
    return lines;
  }

  /**
   * Build party jumps from party jump events
   */
  private buildPartyJumps(): string[] {
    const lines: string[] = [];

    if (!this.song.partyJumps || this.song.partyJumps.length === 0) {
      return lines;
    }

    // Extract jump start and end points from the events
    // We expect pairs of start/end events
    const jumpPairs: Array<[number, number]> = [];
    let jumpStart: number | null = null;

    for (const jump of this.song.partyJumps) {
      if (jump.type === "start") {
        jumpStart = jump.measure;
      } else if (jump.type === "end" && jumpStart !== null) {
        // Shift measure 0 to 1 (HamBuild uses 1-based indexing)
        const hamBuildStart = Math.max(1, jumpStart);
        const hamBuildEnd = Math.max(1, jump.measure);
        jumpPairs.push([hamBuildStart, hamBuildEnd]);
        jumpStart = null;
      }
    }

    if (jumpPairs.length > 0) {
      lines.push("(partyjumps");
      for (const [from, to] of jumpPairs) {
        lines.push(`  (${from} ${to})`);
      }
      lines.push(")");
    }

    return lines;
  }

  /**
   * Build battle section from battle steps (optional - HamBuild auto-generates if omitted)
   */
  private buildBattle(): string[] {
    const lines: string[] = [];

    if (!this.song.battleSteps || this.song.battleSteps.length === 0) {
      return lines;
    }

    lines.push("(battle");

    // Sort by measure to ensure chronological order
    const sortedEvents = [...this.song.battleSteps].sort((a, b) => a.measure - b.measure);

    for (const event of sortedEvents) {
      // Shift measure 0 to 1 (HamBuild uses 1-based indexing)
      const hamBuildMeasure = Math.max(1, event.measure);
      
      const eventType = this.mapBattleEventType(event.type);
      if (eventType) {
        lines.push(`  (${hamBuildMeasure} ${eventType})`);
      }
    }

    lines.push(")");
    return lines;
  }

  /**
   * Map Boomy battle event types to HamBuild battle event types (documented in HamBuild)
   */
  private mapBattleEventType(type: string): string | null {
    const typeMap: Record<string, string> = {
      "battle_reset": "battle_both_idle",
      "player1_solo": "battle_player1_dance",
      "player2_solo": "battle_player2_dance",
      "minigame_start": "battle_minigame_start",
      "minigame_idle": "battle_minigame_idle",
      "minigame_end": "battle_minigame_end",
      "player1_wins": "battle_player1_dance",
      "player2_wins": "battle_player2_dance",
    };
    return typeMap[type] || null;
  }
  private buildCameraEvents(difficulty: string, cameras: Array<{beat: number, camera: string}>): string[] {
    const lines: string[] = [];

    if (!cameras || cameras.length === 0) {
      return lines;
    }

    // Map Boomy camera positions to HamBuild camera events
    const cameraLines: Array<[number, string]> = [];

    for (const cam of cameras) {
      // Shift beat 0 to 1 (HamBuild uses 1-based indexing)
      const hamBuildBeat = Math.max(1, cam.beat);
      
      const hamBuildCamera = this.mapCameraPosition(cam.camera);
      if (hamBuildCamera) {
        // Convert beat to measure.beat format (beat 1-4 per measure)
        const measure = Math.floor((hamBuildBeat - 1) / 4) + 1;
        const beatInMeasure = ((hamBuildBeat - 1) % 4) + 1;
        const measureBeat = `${measure}.${beatInMeasure}`;
        cameraLines.push([hamBuildBeat, `${measureBeat} ${hamBuildCamera}`]);
      }
    }

    // Sort by beat
    cameraLines.sort((a, b) => a[0] - b[0]);

    if (cameraLines.length > 0) {
      const fieldName = difficulty === "expert" ? "venue" :
                        difficulty === "medium" ? "venue_m" : "venue_e";

      lines.push(`(${fieldName}`);
      for (const [, cameraLine] of cameraLines) {
        lines.push(`  (${cameraLine})`);
      }
      lines.push(")");
    }

    return lines;
  }

  /**
   * Map Boomy camera positions to HamBuild camera events
   */
  private mapCameraPosition(position: string): string | null {
    const positionMap: Record<string, string> = {
      "VENUE": "camera_venue",
      "CLOSEUP": "camera_closeup",
      "FAR": "camera_far",
      "MOVEMENT": "camera_movement",
      "NEAR": "camera_near",
      "WIDE": "camera_wide",
      "Area1_NEAR": "camera_area1_near",
      "Area1_MOVEMENT": "camera_area1_movement",
      "Area1_WIDE": "camera_area1_wide",
      "Area1_FAR": "camera_area1_far",
      "Area2_NEAR": "camera_area2_near",
      "Area2_MOVEMENT": "camera_area2_movement",
      "Area2_WIDE": "camera_area2_wide",
      "Area2_FAR": "camera_area2_far",
      "Area3_NEAR": "camera_area3_near",
      "Area3_MOVEMENT": "camera_area3_movement",
      "Area3_WIDE": "camera_area3_wide",
      "Area3_FAR": "camera_area3_far",
    };
    return positionMap[position] || null;
  }

  /**
   * Build events section from song events and battle events
   */
  private buildEventsSection(): string[] {
    const lines: string[] = [];
    const eventLines: Array<[number, string]> = [];

    // Map Boomy event types to HamBuild format
    for (const event of this.song.events || []) {
      const eventType = this.mapSongEventType(event.type);
      if (eventType) {
        // Shift beat 0 to 1 (HamBuild uses 1-based indexing)
        const hamBuildBeat = Math.max(1, event.beat);
        eventLines.push([hamBuildBeat, eventType]);
      }
    }

    // Sort events by beat chronologically
    eventLines.sort((a, b) => a[0] - b[0]);

    if (eventLines.length > 0) {
      lines.push("(events");
      for (const [beat, eventType] of eventLines) {
        lines.push(`  (${beat} ${eventType})`);
      }
      lines.push(")");
    }

    return lines;
  }

  /**
   * Map Boomy song event types to HamBuild event types
   */
  private mapSongEventType(type: string): string | null {
    const typeMap: Record<string, string> = {
      "music_start": "music_start",
      "perform_start": "perform_start",
      "perform_end": "perform_end",
      "freestyle_start": "freestyle_start",
      "freestyle": "freestyle_start", // Alias
      "freestyle_end": "freestyle_end",
      "music_end": "music_end",
      "preview": "preview",
      "end": "end",
    };
    return typeMap[type] || null;
  }

  /**
   * Build a single routine (expert, medium, easy, beginner)
   */
  private buildRoutine(difficulty: string, moves: MoveEvent[]): string[] {
    const lines: string[] = [];

    lines.push(`(${difficulty}`);

    // Sort moves by measure to ensure chronological order
    const sortedMoves = [...moves].sort((a, b) => a.measure - b.measure);

    for (const move of sortedMoves) {
      lines.push(this.formatMoveCommand(move));
    }

    lines.push(")");

    return lines;
  }

  /**
   * Format a single move command with its features
   * Example: (step_side_and_clap_lights_v0 flip clear_left_footik_out)
   */
  private formatMoveCommand(move: MoveEvent): string {
    // Build the move name: move_name_song_v#
    // The move name should already be in the correct format from the move library
    const moveName = this.buildMoveName(move);

    // Get enabled experimental features
    const features = this.getEnabledFeatures(move);

    // Combine move name and features
    if (features.length > 0) {
      return `  (${moveName} ${features.join(" ")})`;
    } else {
      return `  (${moveName})`;
    }
  }

  /**
   * Build the move name in HamBuild format
   * HamBuild expects move names with song names: rest_pondereplay_v1000, step_out_and_clap_l_electricboogie_v0, etc.
   */
  private buildMoveName(move: MoveEvent): string {
    // The clip field already contains the full name with song: rest_pondereplay_v1000, etc.
    // Special case: generic section/rest/freestyle moves need to be output with their generic names
    if (move.clip.startsWith("rest_lights_") || 
        move.clip.startsWith("freestyle_") || 
        move.clip.startsWith("section_") || 
        move.clip.startsWith("perform_")) {
      // These are generic structural moves, use clip as-is (they already have the right format)
      return move.clip;
    }

    // For regular moves, the clip field is already in the correct HamBuild format
    // Example: rest_pondereplay_v1000, step_out_and_clap_l_electricboogie_v0, finishing_move_thatpower_v1099
    return move.clip;
  }

  /**
   * Get all enabled experimental features for a move
   */
  private getEnabledFeatures(move: MoveEvent): string[] {
    if (!move.experimentalFeatures) {
      return [];
    }

    const features: string[] = [];

    // All possible feature keys
    const featureKeys = [
      "clear_left_footik_in",
      "clear_left_footik_out",
      "clear_right_footik_in",
      "clear_right_footik_out",
      "set_left_footik_in",
      "set_left_footik_out",
      "set_right_footik_in",
      "set_right_footik_out",
      "flip",
      "loop_in",
      "loop_out",
      "loop_symmetric_in",
      "loop_symmetric_out",
      "merge_in",
      "sequence",
    ] as const;

    for (const key of featureKeys) {
      if (move.experimentalFeatures[key as keyof typeof move.experimentalFeatures]) {
        features.push(key);
      }
    }

    return features;
  }

  /**
   * Escape special characters for DTA format (Lisp-like)
   */
  private escapeDtaString(str: string): string {
    return str
      .replace(/\\/g, "\\\\") // Escape backslashes first
      .replace(/"/g, '\\"')   // Escape quotes
      .replace(/\n/g, "\\n")  // Escape newlines
      .replace(/\r/g, "\\r"); // Escape carriage returns
  }

  /**
   * Write DTA file to disk using Electron APIs
   */
  async writeToDisk(outputPath: string): Promise<void> {
    const dtaContent = this.generateDta();
    const fileName = `${this.song.name || "song"}.hamproj`;
    const filePath = `${outputPath}/${fileName}`;

    // Use Electron API to write file
    if (typeof window !== "undefined" && (window as any).electronAPI?.writeFile) {
      await (window as any).electronAPI.writeFile(filePath, dtaContent);
    } else {
      throw new Error("Electron API not available for file writing");
    }
  }
}

/**
 * Convert song to HamBuild DTA format and save to file
 */
export async function convertToHamBuildDta(song: Song, outputPath: string): Promise<{ success: boolean; filePath: string; error?: string }> {
  try {
    const builder = new HamBuildDtaBuilder(song);
    await builder.writeToDisk(outputPath);
    const fileName = `${song.name || "song"}.hamproj`;
    return {
      success: true,
      filePath: `${outputPath}/${fileName}`,
    };
  } catch (error) {
    return {
      success: false,
      filePath: "",
      error: error instanceof Error ? error.message : String(error),
    };
  }
}
